apiVersion: bossnet.io/v1
kind: BossnetWorkPool
metadata:
  labels:
    app.kubernetes.io/name: bossnet-operator
    app.kubernetes.io/managed-by: kustomize
  name: external-pool
spec:
  deploymentLabels:
    deployment: label
  type: process
  server:
    remoteApiUrl: https://my-server.example.com
  workers: 3
