# See https://github.com/helm/chart-testing#configuration
charts:
  - deploy/charts/bossnet-operator
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 60s
release-label: bossnet-operator
