---
name: Labeler

"on":
  issues:
    types:
      - opened

jobs:
  apply_label:
    name: Apply bossnet-operator label to all issues
    runs-on: ubuntu-latest
    steps:
      - name: Apply bossnet-operator label to all issues
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['bossnet-operator']
            })
